ksef:
    nip: "6793194113"
    url: "https://api-test.ksef.mf.gov.pl/v2"
    token_path: "./token.txt"
    public_key_path: ""
    form:
        system_code: "FA (3)"
        schema_version: "1-0E"
        value: "FA"

sqlite:
    db_path: "data/ksef-integration-test.db"

server:
    port: "8080"

runonce:
    xml_path: ""

user:
    max_retries: 5
